### ISSUE TITLE
Find a way to detect new posts or changes

### ISSUE THREAD

**Issue by daklassen** [adessoAG/jekyll2cms#11]
The application should only process new files, by adding them to the extern database.

**Task:** Find a way to detect new posts or changes and to only process these changes.

**Comment by shsanayei** [comment]
Maybe generating a hash value for each post will work out to detect modified posts. 
Each time a post gets created, a hash value for that post will be generated and saved in the database. When the application is checking the posts, it will generate a hash value from the posts and compare it to the existing value. If it differs from the existing one, then the post was modified. 

For detecting new Posts the _Git_ class may have some methods.
