### ISSUE TITLE
How should we output information to the console?

### ISSUE THREAD

**Issue by daklassen** [adessoAG/jekyll2cms#26]
**My solution propsal:** 
- Deactivate spring logger on INFO level
- Use spring logger for technical error
- Print any info on System.out
- Use System.err for "logical" errors (e.g. "repo already cloned")

**Comment by shsanayei** [comment]
We need to log all necessary information. 
Is actually a duplicate to #36.
Actually, #36 is a duplicate of this, but I already worked on #36.
