### ISSUE TITLE
The post_id in the table post_meta_data doesn't get assigned to metadata records.

### ISSUE THREAD

**Issue by shsanayei** [adessoAG/jekyll2cms#33]
The post_id in the table post_meta_data doesn't get assigned to metadata records (see image below).
We may need to rewrite the way how we parse the metadata information of markdown files or the way how we save the data in the database using the migrate() method of the CmdService class.

![bug](https://cloud.githubusercontent.com/assets/28383530/26671242/09361026-46b5-11e7-8f33-4674883e9260.PNG)

**Comment by daklassen** [comment]
I think that's not really a bug. Currently we are saving an unfinished version of `PostMetaData` (see the TODO in `migrate `method in `CmdService`). I used this snippet for testing:

```
Image testImage = new Image("path/to/image.png", ".png"); 
persistenceService.saveImage(testImage); 
ArrayList<Image> images = new ArrayList<>(); 
images.add(testImage); 
Post testPost = new Post("content_asdsaklj asjldka skldjasl kdjalsk daklsdjal skdjlkalsk", "teaser_sadfsadfasdfasdf", images); 
persistenceService.savePost(testPost); 
testImage.setPost(testPost); 
persistenceService.saveImage(testImage); 
metaData.setPost(testPost); 
```

**Comment by shsanayei** [comment]
Oh, I see. Ok, then it's just a task.

**Comment by shsanayei** [comment]
The problem is that we have the metadata as yaml/markdown syntax on the one hand and the post as html syntax on the other hand. And from the html code we extract the image data for our image object. 
So we parse the markdown files first to extract the header and save it to database and then we parse the html files. They are both different type of files and are "disconnected". We must find a way to know which markdown file belongs to which html file so we can assign the post to the metadata...

>  Image testImage = new Image("path/to/image.png", ".png"); 
persistenceService.saveImage(testImage); 
ArrayList<Image> images = new ArrayList<>(); 
images.add(testImage); 
Post testPost = new Post("content_asdsaklj asjldka skldjasl kdjalsk daklsdjal skdjlkalsk", "teaser_sadfsadfasdfasdf", images); 
persistenceService.savePost(testPost); 
testImage.setPost(testPost); 
persistenceService.saveImage(testImage); 
metaData.setPost(testPost);
