### ISSUE TITLE
Create job for pulling devblog from GitHub

### ISSUE THREAD

**Issue by shsanayei** [adessoAG/jekyll2cms#50]
Create a job that pulls regularly (at a defined time) the devblog repository.

**Comment by ceverke** [comment]
Created Application Lifecycle for jekyll2cms - will be implemented within this ticket, too

**Comment by ceverke** [comment]
[application_lifecycle.pdf](https://github.com/adessoAG/jekyll2cms/files/1164728/application_lifecycle.pdf)
