### ISSUE TITLE
XML files inside assets/first-spirit-xml must also be deleted when deleting a post file.

### ISSUE THREAD

**Issue by shsanayei** [adessoAG/jekyll2cms#60]
When Jekyll2Cms pulls changes from the configured repository and copies the xml files to the specified first-spirit-xml directory, it does not regard deleted files. 

The application must also recognize deleted files and delete the xml equivalents to those files from the first-spirit-xml directory as well.

**Comment by Calle-Lo** [comment]
The Method pushRep gets an List<DiffEntry> entries in the Parameterlist.
The Method copyGeneratedXmlFiles gets the same Parameter.

The Method iterates through the List and looks for entries which has the typ DELETE and delete them from the local Repository in the copyGeneratedXmlFiles Method and  add it for the commit in the pushRepo Method.
