### ISSUE TITLE
Add git hooks/webhooks for pre-commit.

### ISSUE THREAD

**Issue by shsanayei** [adessoAG/jekyll2cms#61]
Create hooks in order to check if the required fields are filled and have a valid format in the Front Matter of the post files before committing.

**Comment by florianluediger** [comment]
@Calle-Lo What's the status on this? Is this still _In Progress_?

**Comment by jo2** [comment]
This feature is now part of the [BlogpostChecker](https://github.com/adessoAG/blogpost-checker). This issue will be closed.
