### ISSUE TITLE
Split `RepoService` in multiple classes

### ISSUE THREAD

**Issue by thombergs** [adessoAG/jekyll2cms#66]
`RepoService` should be split up in multiple classes that are better testable. For example:

* `GitRepoCloner`
* `GitRepoPuller`
* `GitRepoDiffer` (checks for changes since the last version)
* `MarkdownTransformer` (runs Jekyll to transform Markdown to XML, reads XML files from the source folder and copies them to the target folder)
* `GitRepoPusher`
*...

each of those classes can then be rather easily covered with unit tests

**Comment by Calle-Lo** [comment]
Split RepoService in multiple classes with the Commit 180.
