### ISSUE TITLE
Establish a connection to a database

### ISSUE THREAD

**Issue by daklassen** [adessoAG/jekyll2cms#9]
In the final result we want to save all posts into a extern database. For the moment its good enough to save posts into a H2 database.

**Task:** Establish a connection to a database create the necessary methods and classes to save posts into this database.

**Comment by shsanayei** [comment]
I think we should create an entity for the image properties so we can store the information in a table and reference the image in the PostMetaInformation entity/table.

For example:
**entity name:** PostImageProperties

**fields:**
- Id
- imageKey
- imageValue
- modifiedTime (maybe this field, too)

**Comment by daklassen** [comment]
What exactly do you want to store into `imageKey` and `imageValue`?

I would expect something like:

- Id
- imageUrl (path to image on the local machine)
- format (e.g. "jpg" or "png")
- lastUpdate (as a Date)

**Comment by shsanayei** [comment]
I actually revised my idea:

Basically, you have a table where you put just properties like URL, format, etc... as keys (or name it property_name).
Then you have another table for post image relationship where you link a post meta data id to a post image property id. In this table you will then put the value of the property.

POST_META_DATA | 
------------ | 
ID | 
TITLE | 
CATEGORIES | 
AUTHOR | 
TAGS | 
DATE | 
MOD_TIME | 

POST_IMAGE_PROPERTY | 
------------ | 
ID | 
PROPERTY_NAME | 
DESCRIPTION | 

POST_IMAGE_RELATION | 
------------ | 
POST_META_DATA_ID| 
POST_IMAGE_PROPERTY_ID | 
PROPERTY_VALUE |
